const jCategory = [
    {
        index:0,
        image:"../images/google.png",
        title:"Web Developer",
        rate:"$900-1200/m",
        av: "Full Time",
        companyName:"Google",
        location:"USA",
        vacany:"01",
        hours:"50h / Week",
        description:"We are seeking a motivated and skilled IT professional to join our dynamic team. The ideal candidate will have a strong background in information technology, with a focus on supporting and enhancing our IT infrastructure. This role involves troubleshooting technical issues, implementing software solutions, and providing exceptional customer service to our internal and external clients.",
        workplace:"Work from home",
        education:"Bachelor’s degree in a relevant field from an accredited university; a master’s degree or relevant certifications may be preferred.",
        exprience:"2 to 5 year(s)"
    },
    {
        index:1,
        image:"../images/uber.png",
        title:"Bussiness Associate",
        rate:"$900-1200/m",
        av: "Part Time",
        companyName:"Uber",
        location:"Canada",
        vacany:"04",
        hours:"20h / Week",
        description:"We are seeking a motivated and skilled IT professional to join our dynamic team. The ideal candidate will have a strong background in information technology, with a focus on supporting and enhancing our IT infrastructure. This role involves troubleshooting technical issues, implementing software solutions, and providing exceptional customer service to our internal and external clients.",
        workplace:"Work from home",
        education:"Bachelor’s degree in a relevant field from an accredited university; a master’s degree or relevant certifications may be preferred.",
        exprience:"2 to 5 year(s)"
    },
    {
        index:2,
        image:"../images/yahoo.png",
        title:"User Experience",
        rate:"$900-1200/m",
        av: "Part Time",
        companyName:"Yahoo",
        location:"USA",
        vacany:"01",
        hours:"20h / Week",
        description:"We are seeking a motivated and skilled IT professional to join our dynamic team. The ideal candidate will have a strong background in information technology, with a focus on supporting and enhancing our IT infrastructure. This role involves troubleshooting technical issues, implementing software solutions, and providing exceptional customer service to our internal and external clients.",
        workplace:"Work from home",
        education:"Bachelor’s degree in a relevant field from an accredited university; a master’s degree or relevant certifications may be preferred.",
        exprience:"2 to 5 year(s)"
    },
    {
        index:3,
        image:"../images/linkedin.png",
        title:"Bussiness Associate",
        rate:"$900-1200/m",
        av: "Part Time",
        companyName:"LinkedIn",
        location:"Unistate",
        vacany:"02",
        hours:"20h / Week",
        description:"We are seeking a motivated and skilled IT professional to join our dynamic team. The ideal candidate will have a strong background in information technology, with a focus on supporting and enhancing our IT infrastructure. This role involves troubleshooting technical issues, implementing software solutions, and providing exceptional customer service to our internal and external clients.",
        workplace:"Work from home",
        education:"Bachelor’s degree in a relevant field from an accredited university; a master’s degree or relevant certifications may be preferred.",
        exprience:"2 to 5 year(s)"
    },
    {
        index:4,
        image:"../images/facebook.png",
        title:"Digital Marketing",
        rate:"$900-1200/m",
        av: "Part Time",
        companyName:"Facebook",
        location:"Viet Nam",
        vacany:"03",
        hours:"20h / Week",
        description:"We are seeking a motivated and skilled IT professional to join our dynamic team. The ideal candidate will have a strong background in information technology, with a focus on supporting and enhancing our IT infrastructure. This role involves troubleshooting technical issues, implementing software solutions, and providing exceptional customer service to our internal and external clients.",
        workplace:"Work from home",
        education:"Bachelor’s degree in a relevant field from an accredited university; a master’s degree or relevant certifications may be preferred.",
        exprience:"2 to 5 year(s)"
    },
    {
        index:5,
        image:"../images/facebook.png",
        title:"Digital Marketing",
        rate:"$900-1200/m",
        av: "Freelance",
        companyName:"Facebook",
        location:"Viet Nam",
        vacany:"03",
        hours:"30h / Week",
        description:"We are seeking a motivated and skilled IT professional to join our dynamic team. The ideal candidate will have a strong background in information technology, with a focus on supporting and enhancing our IT infrastructure. This role involves troubleshooting technical issues, implementing software solutions, and providing exceptional customer service to our internal and external clients.",
        workplace:"Work from home",
        education:"Bachelor’s degree in a relevant field from an accredited university; a master’s degree or relevant certifications may be preferred.",
        exprience:"2 to 5 year(s)"
    },
]